import { z } from "zod";
import type { PaymentMethod } from "@prisma/client";

// Mirrors the POS request shapes in backend/openapi.yaml (lowercase on the wire).
const money = z.number().finite().min(0).max(1_000_000);
const method = z
  .enum(["cash", "card", "other"])
  .transform((v) => v.toUpperCase() as Extract<PaymentMethod, "CASH" | "CARD" | "OTHER">);

const cartItem = z.object({
  productId: z.string().min(1).max(64),
  quantity: z.number().int().min(1).max(10_000),
});

export const manualDiscountSchema = z.object({
  type: z.enum(["percentage", "fixed"]).transform((v) => v.toUpperCase() as "PERCENTAGE" | "FIXED"),
  value: z.number().finite().positive().max(1_000_000),
  reason: z.string().trim().max(200).optional(),
});
export type ManualDiscount = z.infer<typeof manualDiscountSchema>;

const cartItems = z.array(cartItem).min(1).max(200);

/** A store discount code (from the discounts module) instead of a manual discount; the two do not combine. */
const discountCode = z.string().trim().min(1).max(30).optional();

export const quoteSchema = z.object({
  items: cartItems,
  discount: manualDiscountSchema.nullish(),
  discountCode,
});

export const customerInputSchema = z.object({
  name: z.string().trim().min(1).max(120).optional(),
  email: z.string().trim().email().max(254).optional(),
  phone: z.string().trim().min(3).max(40).optional(),
});
export type CustomerInput = z.infer<typeof customerInputSchema>;

export const createSaleSchema = z.object({
  items: cartItems,
  discount: manualDiscountSchema.nullish(),
  discountCode,
  /** An existing customer, or details for a new one. */
  customerId: z.string().min(1).max(64).optional(),
  customer: customerInputSchema.optional(),
  payments: z
    .array(
      z.object({
        method,
        /** What is applied to the sale. For cash this is the part of the tendered cash that pays for it. */
        amount: money.refine((n) => n > 0, "A payment must be more than zero"),
        /** Cash only: what the customer handed over. */
        tendered: money.optional(),
      })
    )
    .min(1)
    .max(6),
  /** Generated by the register once per sale attempt, so a retry cannot ring the sale up twice. */
  clientRequestId: z.string().trim().min(8).max(80).optional(),
});
export type CreateSaleInput = z.infer<typeof createSaleSchema>;

export const listSalesQuerySchema = z.object({
  /** An order number, or part of a customer email or name. */
  q: z.string().trim().min(1).max(100).optional(),
  from: z.coerce.date().optional(),
  to: z.coerce.date().optional(),
  limit: z.coerce.number().int().min(1).max(100).optional().default(20),
  offset: z.coerce.number().int().min(0).optional().default(0),
});
export type ListSalesQuery = z.infer<typeof listSalesQuerySchema>;

export const returnSchema = z.object({
  items: z
    .array(
      z.object({
        orderItemId: z.string().min(1).max(64),
        quantity: z.number().int().min(1).max(10_000),
      })
    )
    .min(1)
    .max(200),
  /** How the money goes back. Defaults to how the sale was mostly paid. */
  refundMethod: method.optional(),
  reason: z.string().trim().max(500).optional(),
  /** Put the items back on the shelf. Default yes; say no for damaged goods. */
  restock: z.boolean().optional(),
});
export type ReturnInput = z.infer<typeof returnSchema>;

export const openShiftSchema = z.object({ openingFloat: money });
export const closeShiftSchema = z.object({
  countedCash: money,
  note: z.string().trim().max(500).optional(),
});

export const productSearchSchema = z.object({
  q: z.string().trim().min(1).max(100).optional(),
  /** Exact barcode or SKU, as a scanner types it. */
  code: z.string().trim().min(1).max(100).optional(),
  limit: z.coerce.number().int().min(1).max(60).optional().default(30),
});

export const customerSearchSchema = z.object({ q: z.string().trim().min(1).max(100).optional() });

export const holdSaleSchema = z.object({
  items: cartItems,
  discount: manualDiscountSchema.nullish(),
  customerId: z.string().min(1).max(64).optional(),
  label: z.string().trim().max(60).optional(),
});

export const dailyReportQuerySchema = z
  .object({ from: z.coerce.date(), to: z.coerce.date() })
  .refine((v) => v.to > v.from, { message: "'to' must be after 'from'" })
  .refine((v) => v.to.getTime() - v.from.getTime() <= 32 * 24 * 60 * 60 * 1000, {
    message: "A report can cover at most 32 days",
  });

export const posSettingsSchema = z.object({
  maxCashierDiscountPercent: z.number().min(0).max(100),
});
